version: "3.3"
services:
  inditextest1:
      build: ./
      ports:
        - "5001:8080"
      extra_hosts:
        - "host.docker.internal:host-gateway"
      container_name: node1
      environment:
        - SPRING_REDIS_HOST=redis
        - SPRING_REDIS_PORT=6379
      networks:
        - mynetwork
  inditextest2:
    build: ./
    ports:
      - "5002:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: node2
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - mynetwork
  inditextest3:
    build: ./
    ports:
      - "5003:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: node3
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - mynetwork
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--save", "''", "--appendonly", "no" ]
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
  proxy:
    build: nginx
    ports:
      - "5000:5000"
    networks:
      - mynetwork
volumes:
  redis_data:
networks:
  mynetwork: